<?php

namespace AppBundle\Repository;

/**
 * TimeStampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeStampRepository extends \Doctrine\ORM\EntityRepository
{
}
