<?php

namespace AppBundle\Repository;

/**
 * TimestampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimestampRepository extends \Doctrine\ORM\EntityRepository
{
}
